# Generated by Django 6.0.1 on 2026-01-22 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=16, unique=True)),
                ('allow_more_than_two', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('persons', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('slot', models.CharField(max_length=50)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('date', 'slot'), name='unique_external_slot_per_day')],
            },
        ),
        migrations.CreateModel(
            name='InternalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('persons', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('slot', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['date'], name='booking_int_date_640904_idx')],
            },
        ),
        migrations.CreateModel(
            name='InternalPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('register_number', models.CharField(max_length=16)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='booking.internalbooking')),
            ],
            options={
                'indexes': [models.Index(fields=['register_number'], name='booking_int_registe_cce1f4_idx')],
            },
        ),
    ]
