# Generated by Django 6.0.1 on 2026-01-22 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeroverride',
            name='remarks',
        ),
    ]
