# Generated by Django 6.0.1 on 2026-07-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_pendingstudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='username',
        ),
    ]
