# Generated by Django 6.0.1 on 2026-07-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_name_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalbooking',
            name='email',
            field=models.EmailField(default='oldbooking@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
