# Generated by Django 6.0.7 on 2026-07-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_internalbooking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalbooking',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='internal_excel/'),
        ),
    ]
